name: Release Branch Images

on:
  workflow_dispatch:

jobs:
  build-gepardec-sso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: source-version
        id: source-version
        run: |
          echo "::set-output name=version::$(cat version)"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: gepardec-sso
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Containerfile
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }}-${{ github.sha }}